name: 'UiPath Check prerelease dependency'
description: 'Wait a designated number of milliseconds'
inputs:
  workspace:  # id of input
    description: 'number of milliseconds to wait'
    required: true
    default: '${{ github.workspace }}'
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
