# This workflow will trigger Datadog Synthetic tests within your Datadog organisation
# For mor

name: Maually trigger this action

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.1.0
    - uses: ./
